export const DESKTOP_PAGE_CONTENT_SIZE_REM = {
  height: 51.875,
  width: 85.0625,
};

export const DESKTOP_PAGE_LAYOUT_OFFSET_REM = {
  bottom: 2.5625,
  left: 2.5625,
  right: 2.5,
  top: 2.625,
};

export const DESKTOP_PAGE_CONTENT_WIDTH_REM = DESKTOP_PAGE_CONTENT_SIZE_REM.width;
export const DESKTOP_PAGE_CONTENT_HEIGHT_REM = DESKTOP_PAGE_CONTENT_SIZE_REM.height;
export const DESKTOP_PAGE_CONTENT_TOP_OFFSET_REM = DESKTOP_PAGE_LAYOUT_OFFSET_REM.top;
export const DESKTOP_PAGE_CONTENT_BOTTOM_OFFSET_REM = DESKTOP_PAGE_LAYOUT_OFFSET_REM.bottom;
export const DESKTOP_PAGE_LEFT_PADDING_REM = DESKTOP_PAGE_LAYOUT_OFFSET_REM.left;
export const DESKTOP_PAGE_RIGHT_PADDING_REM = DESKTOP_PAGE_LAYOUT_OFFSET_REM.right;
export const DESKTOP_PAGE_HORIZONTAL_PADDING_REM = DESKTOP_PAGE_LAYOUT_OFFSET_REM.right;
