import {
  DESKTOP_PAGE_CONTENT_BOTTOM_OFFSET_REM,
  DESKTOP_PAGE_CONTENT_HEIGHT_REM,
  DESKTOP_PAGE_CONTENT_TOP_OFFSET_REM,
  DESKTOP_PAGE_CONTENT_WIDTH_REM,
  DESKTOP_PAGE_LEFT_PADDING_REM,
  DESKTOP_PAGE_RIGHT_PADDING_REM,
} from "@/shared/constants/Layout.constant";

import type { ProcedureTag } from "./Procedure.types";

export const PROCEDURE_CONTENT_WIDTH_REM = DESKTOP_PAGE_CONTENT_WIDTH_REM;
export const PROCEDURE_CONTENT_HEIGHT_REM = DESKTOP_PAGE_CONTENT_HEIGHT_REM;
export const PROCEDURE_CONTENT_TOP_OFFSET_REM = DESKTOP_PAGE_CONTENT_TOP_OFFSET_REM;
export const PROCEDURE_CONTENT_BOTTOM_OFFSET_REM = DESKTOP_PAGE_CONTENT_BOTTOM_OFFSET_REM;
export const PROCEDURE_PAGE_LEFT_PADDING_REM = DESKTOP_PAGE_LEFT_PADDING_REM;
export const PROCEDURE_PAGE_RIGHT_PADDING_REM = DESKTOP_PAGE_RIGHT_PADDING_REM;
export const MIN_PROCEDURE_SCALE = 0.32;

export const PROCEDURE_BODY_HEIGHT_REM = 47.875;
export const PROCEDURE_LEFT_PANEL_WIDTH_REM = 27.9375;
export const PROCEDURE_RIGHT_PANEL_WIDTH_REM = 56.125;

const PROCEDURE_TAG_LABELS = [
  "# 컷",
  "# 펌",
  "# 염색",
  "# 클리닉",
  "# 다운펌",
  "# 매직",
  "# 드라이",
  "# 남자",
  "# 여자",
  "# 기타",
];

export const PROCEDURE_TAGS: ProcedureTag[] = PROCEDURE_TAG_LABELS.map((label, index) => ({
  id: `procedure-tag-${index + 1}`,
  label,
  selected: false,
}));

export const PROCEDURE_MEMO_MAX_LENGTH = 500;
